name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ObsidianPublisher/actions/.github/workflows/deploy.yml@main
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
